export const carros = [
    {
        id: 1,
        marca: "BMW 325 E36",
        nome: "BMW",
        ano: 1994,
        cor: "Vermelha",
        cambio: "Automático",
        valor: "R$ 95.000",
        path: '/bmw',
        foto: "src/Assets/Images/bmw.png",
        picture: "src/Assets/Images/bmw.jpg",
        text: "• Motor 6 cilindros 192cv a Gasolina • Câmbio automático • Ar-condicionado, vidros e retrovisores elétricos e trava • Bancos de couro com regulagem elétrica • Painel original com rádio • Manual, chave reserva • 81500km • Placa Preta",
    },
    {
        id: 2,
        marca: "PUMA GTI",
        nome: "Puma",
        ano: 1981,
        cor: "Branca",
        cambio: "Manual",
        valor: "R$ 78.000",
        path: '/puma',
        foto: "src/Assets/Images/puma.png",
        picture: "src/Assets/Images/puma.jpg",
        text: "• Ano 1981 •Branco • Motor 1600 a Gasolina • Câmbio manual 4 marchas • Rodas originais com pneus novos • Vidros originais • Painel original com todos os instrumentos originais PUMA • Rádio Bosch • Placa Preta",
    },
    {
        id: 3,
        marca: "MERCEDES E350",
        nome: "Mercedes",
        ano: 2007,
        cor: "Prata",
        cambio: "Automática",
        valor: "R$ 115.000",
        path: '/mercedes',
        foto: "src/Assets/Images/mercedes.png",
        picture: "src/Assets/Images/mercedes.jpg",
        text: "Veículo restaurado com a mecânica e interior cem por cento. Combinacao de cores unica. Placa preta com alto indice de originalidade"
    },
    {
        id: 4,
        marca: "JEEP WILLYS",
        nome: "Jeep",
        ano: 1960,
        cor: "Cinza",
        cambio: "Manual",
        valor: "R$ 138.000",
        path: '/jeep',
        foto: "src/Assets/Images/jeep.png",
        picture: "src/Assets/Images/jeep.jpg",
        text: "Veículo restaurado com a mecânica e interior cem por cento. Combinacao de cores unica. Placa preta com alto indice de originalidade"
    },
    {
        id: 5,
        marca: "FORD GALAXY LANDAU",
        nome: "Ford",
        ano: 1979,
        cor: "Cinza",
        cambio: "Automática",
        valor: "R$ 135.000",
        path: '/landau',
        foto: "src/Assets/Images/landau.png",
        picture: "src/Assets/Images/landau.jpg",
        text: "Excelente apresentação, conservação e originalidade. Dispensa comentários. Um clássico que foi Produzido até 1983, chama muita atenção por onde passa. Chassi intacto, carroceria alinhada, lataria lisa, com pintura e teto de vinil impecável e no mesmo padrão do original. Pequenos detalhes de época mas nada que denigre a integralidade e robustez do motor V8 302. Cofre do motor impecável, com pintura e parafusos zincadas no padrão todo original. Motor original e câmbio hidramático. (Automático) Mecânica (motor, transmissão, freios e suspensão) revisada e em justo funcionamento. Interior impecável com forro dos bancos e carpete do assoalho. Equipado de fábrica com ar condicionado, direção hidráulica, vidros verdes, parabrisa degradê. Instalado rádio antigo com Tojo + alto falantes triaxiais e jogo de pneus novos com banda branca.",
    },
    {
        id: 6,
        marca: "FUSCA 1500",
        nome: "Volkswagen",
        ano: 1973,
        cor: "Azul",
        cambio: "Manual",
        valor: "R$ 85.000",
        path: '/fusca',
        foto: "src/Assets/Images/fusca.png",
        picture: "src/Assets/Images/fusca.jpg",
        text: "•Motor 1500 a Gasolina •Faróis Cibié e Lanternas traseiras Polimatic originais •Interior Areia novo •Faróis de milha Cibié de época •Luz de neblina Carello de époc •Pára-choques do fusca 1303 do fusca americano •Retrovisor de época raro •Rodas originais datadas •Pneus Continental novos •Vidros originais •Tapeçaria branco areia •Rádio de época •Ar condicionado elétrico •Manual e chave reserva Mais de R$ 20.000,00 em acessórios de época, veículo com restauro de excelente qualidade."
    },
    {
        id: 7,
        marca: "PONTIAC CATALINA",
        nome: "Pontiac",
        ano: 1951,
        cor: "Vermelha",
        cambio: "Automático",
        valor: "R$ 210.000",
        path: '/pontiac',
        foto: "src/Assets/Images/pontiac.png",
        picture: "src/Assets/Images/pontiac.jpeg",
        text: "Veículo restaurado com a mecânica e interior cem por cento. Combinacao de cores unica. Placa preta com alto indice de originalidade"
    },
    {
        id: 8,
        marca: "MERCEDES 450SLC",
        nome: "Mercedes",
        ano: 1980,
        cor: "Preta",
        cambio: "Automático",
        valor: "R$ 195.000",
        path: '/slc',
        foto: "src/Assets/Images/450slc.png",
        picture: "src/Assets/Images/450slc.jpg",
        text: "Carro a mais de 6 anos com um colecionador, com uma excelente procedência e uma excelente conservação. E revisão completa na parte elétrica e mecânica, com todas as peças originais da mercedes, troca de carpetes. O Mercedes 450 SLC é alimentado por um motor oito cilindros na V atmosférico desenvolvendo um binário máximo de 360 Nm a 3000 rpm e uma potência máxima de 218 cv a 5000 rpm transmitida às rodas traseiras de 14 polegadas através de uma caixa automática de 3 velocidades. Placa Preta"
    },
    {
        id: 9,
        marca: "FORD RURAL WILLYS LUXO",
        nome: "Ford",
        ano: 1964,
        cor: "Vermelha",
        cambio: "Manual",
        valor: "R$ 110.000",
        path: '/rural',
        foto: "src/Assets/Images/rural.png",
        picture: "src/Assets/Images/rural.jpg",
        text: "Combustivel - Gasolina 5 Marchas Freio Dianteiro a Disco Pneus - BF GOODRICH 31 ``X 10.5`` Ar - Condicionado Vidros Elétricos Conta Giros, Vacuometro, Voltimetro, Amperimetro, Bussola, Inclinometro Bancos de Couro Sensor de Estacionamento Cambão 4 Fárois de Milha"
    }
]
export const vehicles = [
    {
        id: 1,
        marca: "BMW 325 E36",
        nome: "BMW",
        ano: 1994,
        cor: "Vermelha",
        cambio: "Automático",
        valor: "R$ 95.000",
        path: '/bmw',
        foto: "src/Assets/Images/bmw.png",
    },
    {
        id: 2,
        marca: "JEEP WILLYS",
        nome: "Jeep",
        ano: 1960,
        cor: "Cinza",
        cambio: "Manual",
        valor: "R$ 138.000",
        path: '/jeep',
        foto: "src/Assets/Images/jeep.png",
    },
    {
        id: 3,
        marca: "PONTIAC CATALINA",
        nome: "Pontiac",
        ano: 1951,
        cor: "Vermelha",
        cambio: "Automático",
        valor: "R$ 210.000",
        path: '/pontiac',
        foto: "src/Assets/Images/pontiac.png",
    }
]
